<h2><?php _e('Scout data', 'scout-units-list'); ?></h2>
<table class="form-table">
    <tbody>
        <tr>
            <th><label for="sul_publish_email"><?php _e('Publish e-mail', 'scout-units-list'); ?></label></th>
            <td>
                <select name="sul_publish_email" id="sul_publish_email" style="width:15em">
                    <?php foreach ($this->publishEmails as $value => $name): ?>
                        <option<?php echo $this->user->getPublishEmail() == $value ? ' selected' : ''; ?>
                            value="<?php echo $this->escape($value); ?>">
                            <?php echo $this->escape($name); ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </td>
        </tr>
        <tr>
            <th><label for="sul_grade"><?php _e('Grade', 'scout-units-list'); ?></label></th>
            <td>
                <input type="text" name="sul_grade" id="sul_grade" class="regular-text"
                    value="<?php echo $this->escape($this->user->getGrade()); ?>" class="regular-text">
            </td>
        </tr>
        <tr>
            <th><label for="sul_duty"><?php _e('Duty', 'scout-units-list'); ?></label></th>
            <td>
                <input type="text" name="sul_duty" id="sul_duty" class="regular-text"
                    value="<?php echo $this->escape($this->user->getDuty()); ?>" class="regular-text">
            </td>
        </tr>
        <tr>
            <th><label for="sul_sex"><?php _e('Sex', 'scout-units-list'); ?></label></th>
            <td>
                <select name="sul_sex" id="sul_sex" style="width:15em">
                    <option value=""><?php _e('Unknown sex', 'scout-units-list'); ?></option>
                    <?php foreach ($this->sexes as $sexKey => $sexName): $selected = $this->user->getSex() == $sexKey ?>
                        <option value="<?php echo $sexKey; ?>"<?php echo $selected ? ' selected' : ''; ?>>
                            <?php echo $this->escape($sexName); ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </td>
        </tr>
    </tbody>
</table>
