<h2><?php _e('Scout data', 'scout-units-list'); ?></h2>
<table class="form-table">
    <tbody>
        <tr>
            <th><?php _e('Publish e-mail', 'scout-units-list'); ?></th>
            <td><?php $value = $this->user->getPublishEmail(); echo array_key_exists($value, $this->publishEmails) ?
                $this->escape($this->publishEmails[$value]) : ''; ?></td>
        </tr>
        <?php $grade = $this->user->getGrade(); if (!empty($grade)): ?>
            <tr>
                <th><?php _e('Grade', 'scout-units-list'); ?></th>
                <td><?php echo $this->escape($grade); ?></td>
            </tr>
        <?php endif; ?>
        <?php $duty = $this->user->getDuty(); if (!empty($duty)): ?>
            <tr>
                <th><?php _e('Duty', 'scout-units-list'); ?></th>
                <td><?php echo $this->escape($duty); ?></td>
            </tr>
        <?php endif; ?>
        <tr>
            <th><?php _e('Sex', 'scout-units-list'); ?></th>
            <td><?php $this->user->isFemale() ? _e('Female', 'scout-units-list') :
                ($this->user->isMale() ? _e('Male', 'scout-units-list') : _e('Unknown sex', 'scout-units-list'));
            ?></td>
        </tr>
    </tbody>
</table>
