<div class="wrap">
    <h1>
        <?php _e('Configuration', 'scout-units-list'); ?>
    </h1>
    <?php echo $this->partial('Partial/Messages', [
        'messages' => $this->messages,
    ]); ?>
    <?php $form = $this->form; $form->start([
        'attr' => [
            'class' => 'sul-form',
        ],
    ]); ?>
        <?php $form->errors(); ?>
        <table class="form-table">
            <tbody>
                <?php $form->row('cacheTtl', 'Form/RowAdmin'); ?>
                <?php $form->row('orderCategoryId', 'Form/RowAdmin'); ?>
                <?php $form->row('orderNoFormat', 'Form/RowAdmin'); ?>
                <?php $form->row('orderNoPlaceholder', 'Form/RowAdmin'); ?>
                <?php $form->row('mapKey', 'Form/RowAdmin'); ?>
                <?php $form->row('mapDefaultLat', 'Form/RowAdmin'); ?>
                <?php $form->row('mapDefaultLng', 'Form/RowAdmin'); ?>
                <?php $form->row('mapDefaultZoom', 'Form/RowAdmin'); ?>
            </tbody>
        </table>
        <?php $form->row('submit', 'Form/RowSubmitAdmin'); ?>
    <?php $form->end(); ?>
</div>
