<div class="wrap">
    <h1>
        <?php _e('Configuration', 'scout-units-list'); ?>
    </h1>
    <?php echo $this->partial('Partial/Messages', [
        'messages' => $this->messages,
    ]); ?>
    <?php $form = $this->form; $form->start([
        'attr' => [
            'class' => 'sul-form',
        ],
    ]); ?>
        <dl>
            <?php $form->row('cacheTtl'); ?>
            <?php $form->row('orderNoFormat'); ?>
            <?php $form->row('orderNoPlaceholder'); ?>
            <?php $form->row('mapKey'); ?>
            <?php $form->row('mapDefaultLat'); ?>
            <?php $form->row('mapDefaultLng'); ?>
            <?php $form->row('mapDefaultZoom'); ?>
            <?php $form->row('submit'); ?>
        </dl>
    <?php $form->end(); ?>
</div>
