<tr class="inline-edit-row inline-edit-row-post inline-edit-post quick-edit-row quick-edit-row-post inline-edit-post inline-editor">
    <td colspan="%colspan%" class="colspanchange">
        <?php $form = $this->form; $form->start([
            'attr' => [
                'class' => 'sul-form',
            ],
        ]); ?>
        <fieldset class="inline-edit-col-left">
            <legend class="inline-edit-legend"><?php echo $this->escape($this->label); ?></legend>
            <div class="inline-edit-col">
                <?php $form->row($this->orderCategoriesDefined ? 'orderId' : 'orderNo', 'Form/RowInline'); ?>
            </div>
        </fieldset>
        <p class="submit inline-edit-save">
            <button type="button" class="button cancel alignleft">Anuluj</button>
            <?php $form->widget('submit'); ?>
            <?php if ($this->orderCategoriesDefined): ?>
                <?php $form->widget('orderNo'); ?>
            <?php endif; ?>
            <br class="clear">
        </p>
        <?php $form->end(); ?>
    </td>
</tr>
