<div class="wrap">
    <?php foreach ($this->messages as $message): ?>
        <p class="message <?php echo $message->type; ?>"><?php echo $this->escape($message->text); ?></p>
    <?php endforeach; ?>
    <h1>
        <?php if (isset($this->position)): ?>
            <?php _e('Edit position', $this->td); ?>
            <a href="<?php $this->link(['action' => 'form']); ?>" class="page-title-action">
                <?php _e('Add position', $this->td); ?>
            </a>
        <?php else: ?>
            <?php _e('Add position', $this->td); ?>
        <?php endif; ?>
    </h1>
    <?php $form = $this->form; $form->start(); ?>
        <dl>
            <?php $form->row('type'); ?>
            <?php $form->row('nameMale'); ?>
            <?php $form->row('nameFemale'); ?>
            <?php $form->row('description'); ?>
            <?php $form->row('leader'); ?>
            <?php $form->row('submit'); ?>
        </dl>
    <?php $form->end(); ?>
</div>
