<div class="wrap">
    <h1>
        <?php if (isset($this->position)): ?>
            <?php _e('Edit position', 'scout-units-list'); ?>
            <a href="<?php $this->link(['action' => 'form']); ?>" class="page-title-action">
                <?php _e('Add position', 'scout-units-list'); ?>
            </a>
        <?php else: ?>
            <?php _e('Add position', 'scout-units-list'); ?>
        <?php endif; ?>
    </h1>
    <?php echo $this->partial('Partial/Messages', [
        'messages' => $this->messages,
    ]); ?>
    <?php $form = $this->form; $form->start(); ?>
        <?php $form->errors(); ?>
        <dl>
            <?php $form->row('type'); ?>
            <?php $form->row('nameMale'); ?>
            <?php $form->row('nameFemale'); ?>
            <?php $form->row('description'); ?>
            <?php $form->row('leader'); ?>
            <?php $form->row('submit'); ?>
        </dl>
    <?php $form->end(); ?>
</div>
