<div class="wrap">
    <?php foreach ($this->messages as $message): ?>
        <p class="message <?php echo $message->type; ?>"><?php echo $this->escape($message->text); ?></p>
    <?php endforeach; ?>
    <h1>
        <?php _e('Positions list', $this->td); ?>
        <a href="<?php $this->link([
            'action' => 'form',
        ]); ?>" class="page-title-action">
            <?php _e('Add new', $this->td); ?>
        </a>
    </h1>

    <ul>
        <?php foreach ($this->positions as $position): ?>
            <li>
                <a href="<?php echo $this->link([
                    'action' => 'form',
                    'id' => $position->getId(),
                ]); ?>"><?php echo $this->escape($position->getNameMale()); ?>/<?php echo $this->escape($position->getNameFemale()); ?></a>
                | <a href="<?php echo $this->link([
                    'action' => 'form',
                    'id' => $position->getId(),
                ]); ?>">edytuj</a>
                | <a href="<?php echo $this->link([
                    'action' => 'delete',
                    'id' => $position->getId(),
                ]); ?>">usuń</a>
            </li>
        <?php endforeach; ?>
    </ul>
</div>
