<div class="wrap">
    <h1>
        <?php _e('Positions list', 'scout-units-list'); ?>
        <a href="<?php $this->link([
            'action' => 'form',
        ]); ?>" class="page-title-action">
            <?php _e('Add new', 'scout-units-list'); ?>
        </a>
    </h1>
    <?php echo $this->partial('Partial/Messages', [
        'messages' => $this->messages,
    ]); ?>
    <ul>
        <?php foreach ($this->positions as $position): ?>
            <li>
                <a href="<?php echo $this->link([
                    'action' => 'form',
                    'id' => $position->getId(),
                ]); ?>"><?php echo $this->escape($position->getNameMale()); ?>/<?php echo $this->escape($position->getNameFemale()); ?></a>
                | <a href="<?php echo $this->link([
                    'action' => 'form',
                    'id' => $position->getId(),
                ]); ?>">edytuj</a>
                | <a href="<?php echo $this->link([
                    'action' => 'delete',
                    'id' => $position->getId(),
                ]); ?>">usuń</a>
            </li>
        <?php endforeach; ?>
    </ul>
    <div class="tablenav bottom">
        <?php echo $this->partial('Partial/PaginationAdmin', [
            'packNo' => $this->positions->packNo,
            'packsCount' => $this->positions->packsCount,
            'totalSize' => $this->positions->totalSize,
        ]); ?>
        <br class="clear">
    </div>
</div>
