<div class="wrap">
    <h1>
        <?php _e('Positions list', 'scout-units-list'); ?>
        <a href="<?php $this->link([
            'action' => 'form',
        ]); ?>" class="page-title-action">
            <?php _e('Add new', 'scout-units-list'); ?>
        </a>
    </h1>
    <?php echo $this->partial('Partial/Messages', [
        'messages' => $this->messages,
    ]); ?>
    <div class="tablenav top">
        <?php echo $this->partial('Partial/PaginationAdmin', [
            'packNo' => $this->positions->packNo,
            'packsCount' => $this->positions->packsCount,
            'totalSize' => $this->positions->totalSize,
        ]); ?>
        <br class="clear">
    </div>
    <table class="wp-list-table widefat fixed striped pages sul-list">
	<thead>
            <tr>
                <th scope="col" id="name" class="manage-column column-primary"><?php _e('Position name', 'scout-units-list'); ?></th>
                <th scope="col" id="type" class="manage-column"><?php _e('Type', 'scout-units-list'); ?></th>
                <th scope="col" id="leader" class="manage-column"><?php _e('Unit leader', 'scout-units-list'); ?></th>
                <th scope="col" id="description" class="manage-column"><?php _e('Description', 'scout-units-list'); ?></th>
            </tr>
	</thead>
	<tbody id="the-list">
            <?php if (count($this->positions) > 0): ?>
                <?php foreach ($this->positions as $position):
                    $positionName = $position->getNameMale() . ' / ' . $position->getNameFemale();
                    $typeName = ScoutUnitsList\Form\UnitAdminForm::getTypeName($position->getType());
                    $editLink = $this->getLink([
                        'action' => 'form',
                        'id' => $position->getId(),
                    ]);
                    $deleteLink = $this->getLink([
                        'action' => 'delete',
                        'id' => $position->getId(),
                    ]);
                ?>
                    <tr>
                        <td class="name column-name has-row-actions column-primary" data-colname="<?php _e('Position name', 'scout-units-list'); ?>">
                            <strong><a href="<?php echo $editLink; ?>" aria-label="<?php echo sprintf(__('&#8220;%s&#8221; (Edit)', 'scout-units-list'), $positionName); ?>"><?php echo $this->escape($positionName); ?></a></strong>
                            <div class="row-actions">
                                <span class="edit"><a href="<?php echo $editLink; ?>"><?php _e('Edit', 'scout-units-list'); ?></a></span> |
                                <span class="trash"><a href="<?php echo $deleteLink; ?>"><?php _e('Delete', 'scout-units-list'); ?></a></span>
                            </div>
                            <button type="button" class="toggle-row"><span class="screen-reader-text"><?php _e('Show more details', 'scout-units-list'); ?></span></button>
                        </td>
                        <td class="type column-type" data-colname="<?php _e('Type', 'scout-units-list'); ?>"><?php echo $this->escape($typeName); ?></td>
                        <td class="leader column-leader" data-colname="<?php _e('Unit leader', 'scout-units-list'); ?>"><?php echo $position->isLeader() ? __('Yes', 'scout-units-list') : __('No', 'scout-units-list'); ?></td>
                        <td class="description column-description" data-colname="<?php _e('Description', 'scout-units-list'); ?>"><?php echo $this->escape($position->getDescription()); ?></td>
                    </tr>
                <?php endforeach; ?>
            <?php else: ?>
                <tr class="no-items">
                    <td colspan="4" class="colspanchange"><?php _e('No positions found.', 'scout-units-list'); ?></td>
                </tr>
            <?php endif; ?>
	</tbody>
	<tfoot>
            <tr>
                <th scope="col" class="manage-column column-primary"><?php _e('Position name', 'scout-units-list'); ?></th>
                <th scope="col" class="manage-column"><?php _e('Type', 'scout-units-list'); ?></th>
                <th scope="col" class="manage-column"><?php _e('Unit leader', 'scout-units-list'); ?></th>
                <th scope="col" class="manage-column"><?php _e('Description', 'scout-units-list'); ?></th>
            </tr>
	</tfoot>
    </table>
    <div class="tablenav bottom">
        <?php echo $this->partial('Partial/PaginationAdmin', [
            'packNo' => $this->positions->packNo,
            'packsCount' => $this->positions->packsCount,
            'totalSize' => $this->positions->totalSize,
        ]); ?>
        <br class="clear">
    </div>
</div>
