<div class="wrap">
    <?php foreach ($this->messages as $message): ?>
        <p class="message <?php echo $message->type; ?>"><?php echo $this->escape($message->text); ?></p>
    <?php endforeach; ?>
    <h1>
        <?php if ($this->unit->getId() != null): ?>
            <?php _e('Edit unit', $this->td); ?>
            <a href="<?php $this->link(array(
                'action' => 'admin-form',
            )); ?>" class="page-title-action">
                <?php _e('Add new', $this->td); ?>
            </a>
        <?php else: ?>
            <?php _e('Add unit', $this->td); ?>
        <?php endif; ?>
    </h1>
    <?php $form = $this->form; $form->start(); ?>
        <dl>
            <?php $form->row('status'); ?>
            <?php $form->row('type'); ?>
            <?php $form->row('subtype'); ?>
            <?php $form->row('sort'); ?>
            <?php $form->row('parentId'); ?>
            <?php $form->row('name'); ?>
            <?php $form->row('nameFull'); ?>
            <?php $form->row('hero'); ?>
            <?php $form->row('heroFull'); ?>
            <?php $form->row('orderNo'); ?>
            <?php $form->row('submit'); ?>
        </dl>
    <?php $form->end(); ?>
</div>
