<div class="wrap">
    <?php foreach ($this->messages as $message): ?>
        <p class="message <?php echo $message->type; ?>"><?php echo $this->escape($message->text); ?></p>
    <?php endforeach; ?>
    <h1>
        <?php printf(__('Edit unit "%s"', 'scout-units-list'), $this->unit->getName()); ?>
    </h1>
    <?php $form = $this->form; $form->start(); ?>
        <?php $form->errors(); ?>
        <dl>
            <?php $form->row('url'); ?>
            <?php $form->row('mail'); ?>
            <?php $form->row('address'); ?>
            <?php $form->row('meetingsTime'); ?>
            <?php $form->label('localizationLat'); ?>
            <dd>
                <?php $form->errors('localizationLat'); ?>
                <?php $form->errors('localizationLng'); ?>
                <?php $form->widget('localizationLat'); ?>
                <?php $form->widget('localizationLng'); ?>
            </dd>
            <?php $form->row('submit'); ?>
        </dl>
    <?php $form->end(); ?>
</div>
