<div class="wrap">
    <h1>
        <?php printf(__('Edit unit "%s"', 'scout-units-list'), $this->unit->getName()); ?>
    </h1>
    <?php echo $this->partial('Partial/Messages', [
        'messages' => $this->messages,
    ]); ?>
    <?php $form = $this->form; $form->start([
        'attr' => [
            'class' => 'sul-form',
        ],
    ]); ?>
        <?php $form->errors(); ?>
        <table class="form-table">
            <tbody>
                <?php $form->row('sort', 'Form/RowAdmin'); ?>
                <?php $form->row('url', 'Form/RowAdmin'); ?>
                <?php $form->row('mail', 'Form/RowAdmin'); ?>
                <?php $form->row('address', 'Form/RowAdmin'); ?>
                <?php $form->row('meetingsTime', 'Form/RowAdmin'); ?>
                <?php $form->row('markerUrl', 'Form/RowAdmin'); ?>
                <?php $form->label('locationLat', 'Form/LabelAdmin'); ?>
                <td>
                    <?php $form->errors('locationLat'); ?>
                    <?php $form->errors('locationLng'); ?>
                    <div id="sul-location-map"></div>
                    <?php $form->widget('locationLat'); ?>
                    <?php $form->widget('locationLng'); ?>
                </td>
            </tbody>
        </table>
        <?php $form->row('submit', 'Form/RowSubmitAdmin'); ?>
    <?php $form->end(); ?>
</div>
