<div class="wrap">
    <h1>
        <?php printf(__('Edit unit "%s"', 'scout-units-list'), $this->unit->getName()); ?>
    </h1>
    <?php echo $this->partial('Partial/Messages', [
        'messages' => $this->messages,
    ]); ?>
    <?php $form = $this->form; $form->start(); ?>
        <?php $form->errors(); ?>
        <dl>
            <?php $form->row('url'); ?>
            <?php $form->row('mail'); ?>
            <?php $form->row('address'); ?>
            <?php $form->row('meetingsTime'); ?>
            <?php $form->label('localizationLat'); ?>
            <dd>
                <?php $form->errors('localizationLat'); ?>
                <?php $form->errors('localizationLng'); ?>
                <div id="sul-localization-map"></div>
                <?php $form->widget('localizationLat'); ?>
                <?php $form->widget('localizationLng'); ?>
            </dd>
            <?php $form->row('submit'); ?>
        </dl>
    <?php $form->end(); ?>
</div>
