<div class="wrap">
    <h1>
        <?php printf(__('Manage persons in unit "%s"', 'scout-units-list'), $this->unit->getName()); ?>
    </h1>
    <?php echo $this->partial('Partial/Messages', [
        'messages' => $this->messages,
    ]); ?>
    <ul>
        <?php foreach ($this->persons as $person): $user = $person->getUser(); $position = $person->getPosition(); ?>
            <li>
                user: <?php echo $this->escape($user->getNiceName()); ?>
                    (<?php echo $this->escape($user->getLogin()); ?>) /
                position: <?php echo $this->escape($position->getNameFemale()); ?> /
                    <?php echo $this->escape($position->getNameFemale()); ?>,
                    <?php echo $position->getDescription() != '' ?
                        '(' . $this->escape($position->getDescription()) . '),' : ''; ?>
                    <?php echo $position->isLeader() ? ' ' . __('leader', 'scout-units-list') : ''; ?>
                <a href="<?php echo $this->link([
                    'action' => 'person-manage',
                    'deletedId' => $person->getId(),
                    'id' => $this->unit->getId(),
                ]); ?>">usuń</a>
            </li>
        <?php endforeach; ?>
    </ul>
    <?php if (isset($this->form)): $form = $this->form; $form->start([
        'attr' => [
            'class' => 'sul-form',
        ],
    ]); ?>
        <?php $form->errors(); ?>
        <dl>
            <?php $form->row('userId'); ?>
            <?php $form->row('positionId'); ?>
            <?php $form->row('orderNo'); ?>
            <?php $form->row('submit'); ?>
        </dl>
    <?php $form->end(); endif; ?>
</div>
