<div class="wrap">
    <h1>
        <?php printf(__('Manage persons in unit "%s"', 'scout-units-list'), $this->unit->getName()); ?>
    </h1>
    <?php echo $this->partial('Partial/Messages', [
        'messages' => $this->messages,
    ]); ?>
    <ul>
        <?php foreach ($this->unit->getPersons() as $person): ?>
            <li>
                user: <?php $user = $person->getUser(); echo $this->escape($user->getNiceName()); ?>
                    (<?php echo $this->escape($user->getLogin()); ?>) /
                position: <?php $position = $person->getPosition(); echo $this->escape($position->getNameFemale()); ?> /
                    <?php echo $this->escape($position->getNameFemale()); ?>,
                    <?php echo $position->getDescription() != '' ?
                        '(' . $this->escape($position->getDescription()) . '),' : ''; ?>
                    <?php echo $position->isLeader() ? ' ' . __('leader', 'scout-units-list') : ''; ?>
                <a href="<?php echo $this->link([
                    'action' => 'person-manage',
                    'deletedId' => $person->getId(),
                    'id' => $this->unit->getId(),
                ]); ?>">usuń</a>
            </li>
        <?php endforeach; ?>
    </ul>
    <h2>
        <?php printf(__('Add person to unit "%s"', 'scout-units-list'), $this->unit->getName()); ?>
    </h2>
    <?php if (isset($this->form)): $form = $this->form; $form->start([
        'attr' => [
            'class' => 'sul-form',
        ],
    ]); ?>
        <?php $form->errors(); ?>
        <table class="form-table">
            <tbody>
                <?php $form->row('userId', 'Form/RowAdmin'); ?>
                <?php $form->row('positionId', 'Form/RowAdmin'); ?>
                <?php $form->row('orderNo', 'Form/RowAdmin'); ?>
            </tbody>
        </table>
        <?php $form->row('submit', 'Form/RowSubmitAdmin'); ?>
    <?php $form->end(); endif; ?>
</div>
